name: vibraguard
description: This app is my solution to the Tractian challenge.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.2

  logger: ^2.0.2
  email_validator: ^2.1.17

  provider: ^6.0.5
  get_it: ^7.6.4
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  http: ^1.1.0
  smooth_page_indicator: ^1.1.0
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  husky: ^0.1.6
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
